### PR TITLE
chaosdaemon: check if qdisc exists before deleting it

### LINKED ISSUE #110: fail to recover network chaos
networkchaos  was not working halfway 
image

chaos-daemon error log
```
2020-01-06T02:37:41.045Z        INFO    chaos-daemon-server     Delete netem    {"Request": "container_id:\"docker://3b45b159bfddcf83602149939bdde8e89643ef47003e1f1b3b15da5ce8564c2e\" "}
2020-01-06T02:37:41.047Z        INFO    chaos-daemon-server     Cancel netem on PID     {"pid": 121865}
2020-01-06T02:37:41.047Z        ERROR   chaos-daemon-server     failed to remove Qdisc  {"error": "invalid argument"}
github.com/go-logr/zapr.(*zapLogger).Error
        /home/pingcap/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/pingcap/chaos-mesh/pkg/chaosdaemon.Cancel
        /home/pingcap/go/src/github.com/pingcap/chaos-mesh/pkg/chaosdaemon/netem.go:98
github.com/pingcap/chaos-mesh/pkg/chaosdaemon.(*Server).DeleteNetem
        /home/pingcap/go/src/github.com/pingcap/chaos-mesh/pkg/chaosdaemon/netem_server.go:51
github.com/pingcap/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_DeleteNetem_Handler
        /home/pingcap/go/src/github.com/pingcap/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:625
google.golang.org/grpc.(*Server).processUnaryRPC
        /home/pingcap/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995
google.golang.org/grpc.(*Server).handleStream
        /home/pingcap/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275
google.golang.org/grpc.(*Server).serveStreams.func1.1
        /home/pingcap/go/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710
```

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>  

In this pr, chaosdaemon will check qdisc exists before deleting it and split large functions into multiple small functions, fix #110

### CODE REVIEW

File: pkg/chaosdaemon/iptables_server.go [hunk 1]
```diff
@@ -51,36 +53,51 @@ func (s *Server) FlushIptables(ctx context.Context, req *pb.IpTablesRequest) (*e
 		return nil, fmt.Errorf("unknown rule direction")
 	}
 
-	action := ""
 	switch rule.Action {
 	case pb.Rule_ADD:
-		action = "-A"
+		err = s.addIptablesRules(ctx, nsPath, format, rule)
```
Comment (mahjonp) [inline pkg/chaosdaemon/iptables_server.go]: IMO, it's not a good idea to pass format and rule into addIptablesRules and build the command at addIptablesRules, i prefer to build the command before executing addIptablesRules.

**Comment by mahjonp** [comment]
When to destroy a ipset? i don't found it.

**Comment by mahjonp** [comment]
And if chaosdaemon got a panic after creating the ipset: ${name}old, how does chaos-mesh clear this temporary ipset?

File: pkg/chaosdaemon/netem.go [hunk 2]
```diff
@@ -94,10 +94,41 @@ func Cancel(netem *pb.Netem, pid uint32) error {
...
 	}
 
+	exist, err := qdiscExists(netemQdisc, handle, link)
+	if err != nil {
+		log.Error(err, "failed to check qdisc", "qdisc", netemQdisc, "link", link)
+		return err
+	}
+
+	if !exist {
+		log.Info("qdisc not exists", "qdisc", netemQdisc)
```
Comment (mahjonp) [inline pkg/chaosdaemon/netem.go]: should use log.Error here?

**Comment by cwen0** [comment]
> When to destroy a ipset? i don't find it. And FlushIpSet is so complicated, why not flush the ipset first and then add ips into it?

The deletion of ipset has no effect on the network chaos and this retained ipset can help us to troubleshoot. @YangKeao PTAL

**Comment by zhouqiang-cl** [comment]
@you06 can you help to test this. Maybe it fix some network issue you have meet

**Comment by YangKeao** [comment]
@mahjonp Aha, `ipset` will not be deleted. 

I think we can add extra delete hook method for two phase reconciler to delete `ipset` on deletion.

Deleting and creating `ipset` for every recover is also acceptable now. After fixing some stability issue about network namespace, `ipset` and `iptables` is stable enough to modify frequently.

**Comment by mahjonp** [comment]
ptal @you06

File: pkg/chaosdaemon/netem.go [hunk 3]
```diff
@@ -94,10 +94,41 @@ func Cancel(netem *pb.Netem, pid uint32) error {
...
 	}
 
+	exist, err := qdiscExists(netemQdisc, handle, link)
+	if err != nil {
+		log.Error(err, "failed to check qdisc", "qdisc", netemQdisc, "link", link)
+		return err
+	}
+
+	if !exist {
+		log.Error(nil, "qdisc not exists", "qdisc", netemQdisc)
```
Comment (mahjonp) [inline pkg/chaosdaemon/netem.go]: I recommend to add a warning message on the log, eg. `it maybe had been removed by accident, or there exists a bug on chaos-mesh`, because you return nil on this case.

File: controllers/networkchaos/partition/types.go [hunk 4]
```diff
@@ -215,7 +215,7 @@ func (r *Reconciler) generateSetName(networkchaos *v1alpha1.NetworkChaos, namePo
 		hasher.Write([]byte(nameRest))
 		hashValue := fmt.Sprintf("%x", hasher.Sum(nil))
 
-		ipsetName = namePrefix + "_" + hashValue[0:17] + "_" + namePostFix
+		ipsetName = namePrefix + "_" + hashValue[0:16] + "_" + namePostFix
```
Comment (mapleFU) [inline controllers/networkchaos/partition/types.go]: Why 17 was changed to 16?

File: pkg/chaosdaemon/ipset_server.go [hunk 5]
```diff
@@ -35,59 +43,105 @@ func (s *Server) FlushIpSet(ctx context.Context, req *pb.IpSetRequest) (*empty.E
...
+	// otherwise swap  them with each other.
+	if err := s.renameIPSet(ctx, nsPath, tmpName, name); err != nil {
+		return nil, err
+	}
+
+	return &empty.Empty{}, nil
+}
+
+func (s *Server) createIPSet(ctx context.Context, nsPath string, name string) error {
+	// ipset name cannot be longer than 31 byte
```
Comment (mapleFU) [inline pkg/chaosdaemon/ipset_server.go]: `31 bytes`

File: controllers/networkchaos/partition/types.go (hunk 4 above)
Comment (cwen0) [reply controllers/networkchaos/partition/types.go]: just want to keep the length constant, because I changed the suffix from `old` to `_old`

Comment (mapleFU) [reply controllers/networkchaos/partition/types.go]: How about writing `const` for a summary length, and use `-` to represent it. It's too hard to catch for me.

Comment (cwen0) [reply controllers/networkchaos/partition/types.go]: why `-`?

Comment (mapleFU) [reply controllers/networkchaos/partition/types.go]: Sorry, I mean minus here.

Comment (cwen0) [reply controllers/networkchaos/partition/types.go]: I will add a comment at here

File: pkg/chaosdaemon/ipset_server.go [hunk 6]
```diff
@@ -35,59 +43,105 @@ func (s *Server) FlushIpSet(ctx context.Context, req *pb.IpSetRequest) (*empty.E
...
+
+	out, err := cmd.CombinedOutput()
+	if err != nil {
+		output := string(out)
+		if !strings.Contains(output, ipsetExistErr) {
+			log.Error(err, "ipset create error", "command", cmd.String(), "output", output)
+			return err
+		}
+
+		cmd := withNetNS(ctx, nsPath, "ipset", "flush", name)
```
Comment (you06) [inline pkg/chaosdaemon/ipset_server.go]: Seems it will return error when the ipset is already exist, in another word, the ipset here is a new one. What's the effect of flushing a new ipset.

Comment (cwen0) [reply pkg/chaosdaemon/ipset_server.go]: the old ipset will be overwrite.

Comment (you06) [reply pkg/chaosdaemon/ipset_server.go]: I misunderstand to logic of creation, it looks good.
